include:
  - local: '/.gitlab/ci/workflow-rules.gitlab-ci.yml'
  - local: '/.gitlab/ci/build.gitlab-ci.yml'
  - local: '/.gitlab/ci/cache.gitlab-ci.yml'
  - local: '/.gitlab/ci/dependency.gitlab-ci.yml'
  - local: '/.gitlab/ci/docs.gitlab-ci.yml'
  - local: '/.gitlab/ci/license.gitlab-ci.yml'
  - local: '/.gitlab/ci/lint.gitlab-ci.yml'
  - local: '/.gitlab/ci/qa.gitlab-ci.yml'
  - local: '/.gitlab/ci/release.gitlab-ci.yml'
  - local: '/.gitlab/ci/specs.gitlab-ci.yml'
