# This config lists the jobs that will be run on omnibus-gitlab project in
# gitlab.com.

generate_ci_config:
  image: "${RUBY_IMAGE}"
  stage: prepare-assets
  script:
    - bundle exec rake ci:config:generate
  artifacts:
    paths:
      - generated-ci-config.yml

trigger-pipeline:
  stage: prepare
  needs:
    - generate_ci_config
  trigger:
    include:
      - artifact: generated-ci-config.yml
        job: generate_ci_config
    strategy: depend
