# Trigger pipeline
E2E:
  stage: qa
  inherit:
    variables: false
  variables:
    RELEASE: $QA_RELEASE
    QA_IMAGE: $QA_IMAGE
    QA_TESTS: $QA_TESTS
    ALLURE_JOB_NAME: $ALLURE_JOB_NAME
    GITLAB_QA_OPTIONS: $GITLAB_QA_OPTIONS
    KNAPSACK_GENERATE_REPORT: $KNAPSACK_GENERATE_REPORT
    TOP_UPSTREAM_SOURCE_PROJECT: $TOP_UPSTREAM_SOURCE_PROJECT
    TOP_UPSTREAM_SOURCE_REF: $TOP_UPSTREAM_SOURCE_REF
    TOP_UPSTREAM_SOURCE_JOB: $TOP_UPSTREAM_SOURCE_JOB
    TOP_UPSTREAM_SOURCE_SHA: $TOP_UPSTREAM_SOURCE_SHA
    TOP_UPSTREAM_MERGE_REQUEST_PROJECT_ID: $TOP_UPSTREAM_MERGE_REQUEST_PROJECT_ID
    TOP_UPSTREAM_MERGE_REQUEST_IID: $TOP_UPSTREAM_MERGE_REQUEST_IID
  trigger:
    project: "gitlab-org/gitlab-qa-mirror"
    branch: $QA_BRANCH
    strategy: depend
  rules:
    - if: '$SKIP_QA_TEST == "true"'
      when: never
    # Because of inherit:variables being false, `PIPELINE_TYPE` isn't available here. :(
    # https://gitlab.com/gitlab-org/gitlab/-/issues/368759
    - if: '$CI_PROJECT_PATH == "gitlab-org/build/omnibus-gitlab-mirror" && $CI_PIPELINE_SOURCE=="pipeline"'
  needs:
    - job: generate-facts
      artifacts: true
    - job: Ubuntu-20.04
      artifacts: false
    - job: Docker
      artifacts: false
    - job: Docker-QA
      artifacts: false
      optional: true

RAT-Trigger:
  image: "${RUBY_IMAGE}"
  stage: qa
  extends: .trigger-cache
  allow_failure: true
  script:
    - bundle exec rake qa:rat:trigger
  rules:
    - if: '$PIPELINE_TYPE == "TRIGGERED_EE_PIPELINE"'
      when: manual
  needs:
    - job: Ubuntu-20.04
      artifacts: false
    - job: Docker-QA
      artifacts: false
      optional: true

RAT-Trigger-FIPS:
  extends:
    - RAT-Trigger
    - .trigger-fips-cache
  variables:
    USE_SYSTEM_SSL: "true"
    RAT_REFERENCE_ARCHITECTURE: "omnibus-gitlab-mrs-fips-ubuntu"
  needs:
    - job: Ubuntu-20.04-fips
      artifacts: false
    - job: Docker-QA
      artifacts: false
      optional: true

GET:Geo:
  image: "${RUBY_IMAGE}"
  stage: qa
  extends: .trigger-cache
  allow_failure: true
  rules:
    - if: '$PIPELINE_TYPE == "TRIGGERED_EE_PIPELINE"'
      when: manual
  script:
    - bundle exec rake qa:get:geo:trigger
  needs:
    - job: Ubuntu-20.04
      artifacts: false
    - job: Docker-QA
      artifacts: false
      optional: true

package_size_check:
  image: "${BUILDER_IMAGE_REGISTRY}/ubuntu_20.04:${BUILDER_IMAGE_REVISION}"
  stage: qa
  extends: .trigger-cache
  script:
    - bundle exec rake build:package:generate_sizefile
    - bundle exec rake check:package_size
  needs:
    - job: Ubuntu-20.04
      artifacts: false
  rules:
    - if: '$PIPELINE_TYPE =~ /TRIGGERED_(CE|EE)_PIPELINE/'

letsencrypt-test:
  extends:
    - .docker-job
    - .trigger-cache
  stage: qa
  script:
    - echo "${CI_REGISTRY_PASSWORD}" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - curl -L "https://github.com/docker/compose/releases/download/1.29.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - bundle exec rake qa:test_letsencrypt
  rules:
    - if: '$PIPELINE_TYPE =~ /TRIGGERED_(CE|EE)_PIPELINE/'
  needs:
    - job: Docker
      artifacts: false

# Nightly pipeline

RAT-Nightly:
  image: "${BUILDER_IMAGE_REGISTRY}/ubuntu_16.04:${BUILDER_IMAGE_REVISION}"
  stage: qa
  extends: .gems-cache
  script:
    - bundle exec rake qa:rat:nightly
  needs:
    - Ubuntu-20.04
  allow_failure: true
  rules:
    - !reference [.default_rules, rules]
    - if: '$PIPELINE_TYPE == "EE_NIGHTLY_BUILD_PIPELINE"'

RAT-Nightly-FIPS:
  image: "${BUILDER_IMAGE_REGISTRY}/ubuntu_16.04:${BUILDER_IMAGE_REVISION}"
  stage: qa
  extends: .gems-cache
  variables:
    USE_SYSTEM_SSL: "true"
    RAT_REFERENCE_ARCHITECTURE: "omnibus-gitlab-mrs-fips"
  script:
    - bundle exec rake qa:rat:nightly
  needs:
    - CentOS-8-fips
  allow_failure: true
  rules:
    - !reference [.default_rules, rules]
    - if: '$PIPELINE_TYPE == "EE_NIGHTLY_BUILD_PIPELINE"'

# Release pipeline

RAT-Tag:
  image: "dev.gitlab.org:5005/cookbooks/gitlab-omnibus-builder/ubuntu_16.04:${BUILDER_IMAGE_REVISION}"
  stage: qa
  extends: .gems-cache
  script:
    - bundle exec rake qa:rat:tag
  needs:
    - Ubuntu-20.04
  allow_failure: true
  rules:
    - !reference [.default_rules, rules]
    - if: '$PIPELINE_TYPE =~ /^EE_(RC|TAG)_BUILD_PIPELINE$/'

check-packages:
  stage: verify
  trigger:
    include: '.gitlab/ci/check-packages.gitlab-ci.yml'
  rules:
    - !reference [.default_rules, rules]
    - if: '$PIPELINE_TYPE =~ /_TAG_BUILD_PIPELINE$/'
