---
# Extended Markdown configuration to enforce no-trailing-spaces rule
# To use this configuration, in the project directory run:
#   markdownlint-cli2 --config doc/.markdownlint/.markdownlint-cli2.yaml 'doc/**/*.md'

extends: "../../.markdownlint-cli2.yaml"
fix: true
config:
  no-trailing-spaces: true
